### ISSUE TITLE
at-rules in CSS fail in many cases

### ISSUE THREAD

**Issue by isagalaev** [highlightjs/highlight.js#153]
Testcase:

``` css
@charset "UTF-8";
@charset 'UTF-8';

@namespace "http://www.w3.org/1999/xhtml";
@namespace 'http://www.w3.org/1999/xhtml';
@namespace svg "http://www.w3.org/2000/svg";
@namespace svg 'http://www.w3.org/2000/svg';

@import "foo.scss";
@import 'foo.scss';
@import url("foo.scss");
@import url('foo.scss');
@import url(foo.scss);

@font-face {
    font-family:foo;
    src:local('bar'), url(bar.ttf);
    }
@media all {
    @media print {
        div {
            color:black;
            }
        }
    }
@supports (display:flexbox) {
    div {
        color:black;
        }
    }
@supports not (display:flexbox) {
    div {
        color:white;
        }
    }
@page {
    width:210mm;
    height:297mm;
    }
@-webkit-keyframes foo {
    0% { top: 0; }
    100% { top: 0; }
    }
@-moz-keyframes foo {
    0% { top: 0; }
    100% { top: 0; }
    }
@-ms-keyframes foo {
    0% { top: 0; }
    100% { top: 0; }
    }
@-o-keyframes foo {
    0% { top: 0; }
    100% { top: 0; }
    }
@keyframes foo {
    0% { top: 0; }
    100% { top: 0; }
    }
```
