### ISSUE TITLE
[Feature-request] codelang attribute 

### ISSUE THREAD

**Issue by CreatorVilius** [highlightjs/highlight.js#1812]
Example:

```html
<pre><code class="js">console.log('Woosh')</code></pre>
```
**Would turn to:**
```html
<pre><code class="hljs javascript bla" codelang="Javascript">console.log('Woosh')</code></pre>
```
So you could use in css

```css
code::before {
     content: attr(codelang);
}
```
