### ISSUE TITLE
yaml not rendered correctly

### ISSUE THREAD

**Issue by erez-o** [highlightjs/highlight.js#2058]
Hi, 

I'm having a problem with my yaml files.

Example yaml file:
```yaml
sidebar:
  Basic Tutorial:
  - Getting Started: docs/getting-started.md
  - Customizing The Sidebar: docs/customizing-the-sidebar.md
  - Customizing The Public Api: docs/customizing-the-public-api.md
  - Discussions: docs/discussions.md
  - Themes and CSS: docs/themes-and-css.md
  More Info:
  - Autodoc Settings: docs/autodocSettings-full-list.md
  - Building Version Documentation: docs/building-version-documentation.md
  - Markdown Cheat Sheet: docs/markdown-cheat-sheet.md
  - Changelog: docs/changelog.md
  - Contact Us: docs/contact-us.md
  - Feature Requests: https://github.com/erez-o/doxiz/issues
autodocSettings: {}
```

rendered as:
![yaml highlight](https://user-images.githubusercontent.com/4282254/59751409-21fe4e80-9289-11e9-8bd6-cf8032f7e460.png)

Using the latest version (9.15.8), also made a fiddle http://jsfiddle.net/f261xec4/

Thx
