### ISSUE TITLE
Suggestion for php language parser

### ISSUE THREAD

**Issue by martindilling** [highlightjs/highlight.js#210]
I've modified the php language a little, just wanted to share it, in case you could use some of it ^^

Some of it would require a little more styling, will post my style (modified monokai_sublime) below.
## Script

``` javascript
    hljs.LANGUAGES.php = function(hljs) {
      var VARIABLE = {
        className: 'variable',
        begin: '\\$+[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'
      };
      var STRINGS = [
        hljs.inherit(hljs.APOS_STRING_MODE, {illegal: null}),
        hljs.inherit(hljs.QUOTE_STRING_MODE, {illegal: null}),
        {
          className: 'string',
          begin: 'b"', end: '"',
          contains: [hljs.BACKSLASH_ESCAPE]
        },
        {
          className: 'string',
          begin: 'b\'', end: '\'',
          contains: [hljs.BACKSLASH_ESCAPE]
        }
      ];
      var NUMBERS = [hljs.BINARY_NUMBER_MODE, hljs.C_NUMBER_MODE];
      var TITLE = {
        className: 'title', begin: hljs.UNDERSCORE_IDENT_RE
      };
      return {
        case_insensitive: true,
        contains: [
          hljs.C_LINE_COMMENT_MODE,
          hljs.HASH_COMMENT_MODE,
          {
            className: 'comment',
            begin: '/\\*', end: '\\*/',
            contains: [{
                className: 'phpdoc',
                begin: '\\s@[A-Za-z]+'
            }]
          },
          {
              className: 'comment',
              excludeBegin: true,
              begin: '__halt_compiler.+?;', endsWithParent: true
          },
          {
            className: 'string',
            begin: '<<<[\'"]?\\w+[\'"]?$', end: '^\\w+;',
            contains: [hljs.BACKSLASH_ESCAPE]
          },
          {
            begin: '\\?>', end: '<\\?php',
            subLanguage: 'xml',
            excludeBegin: true, excludeEnd: true
          },
          {
            className: 'preprocessor',
            begin: '<\\?php',
            relevance: 10
          },
          {
            className: 'preprocessor',
            begin: '\\?>'
          },
          {
            className: 'namespace',
            beginWithKeyword: true, end: ';',
            keywords: 'namespace',
            excludeEnd: true
          },
          {
            className: 'alias',
            beginWithKeyword: true, end: ';',
            keywords: 'use',
            excludeEnd: true,
            contains: [
              {
                lexems: '[a-zA-Z\\\\][a-zA-Z0-9_\\\\]*',
                className: 'keyword',
                begin: '[a-zA-Z0-9_\x7f-\xff\\\\]+'
              }
            ]
          },
          VARIABLE,
          {
            className: 'keyword',
            begin: '\\b((a(bstract|nd|rray|s))|(c(a(llable|se|tch)|lone|on(st|tinue)))|(d(e(clare|fault)|ie|o))|(e(cho|lse(if)?|mpty|nd(declare|for(each)?|if|switch|while)|val|x(it|tends)))|(f(inal|or(each)?))|(g(lobal|oto))|(i(f|mplements|n(clude(_once)?|st(anceof|eadof)|terface)|sset))|(p(r(i(nt|vate)|otected)|ublic))|(re(quire(_once)?|turn))|(s(tatic|witch))|(t(hrow|r(ait|y)))|(u(nset|se))|(__halt_compiler|break|list|new|(x)?or|var|while))\\b'
          },
          {
            className: 'keyword',
            begin: '(->|\\-\\-|\\+\\+|\\-|\\+|\\*|/|%|(!|&&|\\|\\|)|<<|>>|~|\\^|&|\\||===|==|!==|!=|<=|>=|<>|<|>|\\.=|\\.|=)'
          },
          {
            className: 'literal',
            begin: '(true|false|null|__(class|dir|f(ile|unction)|line|method|namespace|trait)__|\\b(on|off|yes|no|nl|br|tab)\\b)'
          },
          {
            className: 'class',
            lexems: '',
            begin: '[a-zA-Z0-9_\x7f-\xff]+::+',
            returnBegin: true,
            contains: [
              {
                className: 'keyword',
                begin: '[a-zA-Z0-9_\x7f-\xff]+'
              }
            ]
          },
          {
            className: 'keyword',
            begin: '::'
          },
          {
            className: 'function',
            beginWithKeyword: true, end: '{',
            keywords: 'function',
            illegal: '\\$|\\[|%',
            contains: [
              {
                className: 'corefunction',
                begin: '(?:(__(?:call|(?:con|de)struct|get|(?:is|un)?set|tostring|clone|set_state|sleep|wakeup|autoload)))'
              },
              TITLE,
              {
                className: 'params',
                begin: '\\(', end: '\\)',
                contains: [
                  'self',
                  VARIABLE,
                  hljs.C_BLOCK_COMMENT_MODE
                ].concat(STRINGS).concat(NUMBERS)
              }
            ]
          },
          {
            className: 'class',
            beginWithKeyword: true, end: '{',
            keywords: 'class',
            illegal: '[:\\(\\$]',
            contains: [
              {
                beginWithKeyword: true, endsWithParent: true,
                keywords: 'extends interface',
                contains: [TITLE]
              },
              TITLE
            ]
          },
          {
            begin: '=>' // No markup, just a relevance booster
          }
        ].concat(STRINGS).concat(NUMBERS)
      };
    } (hljs);
```
## Style

As i said, here's my modified version of monokai_sublime, matches what it looks like in sublime a lot better:

``` css
    pre code {
      display: block;
      /*padding: 0.5em;
      background: #23241f;*/
    }
    pre .tag,
    pre code {
      color: #f8f8f2;
    }
    pre .header {
      color: #F92672;
    }
    pre .strongemphasis,
    pre .strong,
    pre .emphasis {
      color: #a8a8a2;
    }
    pre .bullet,
    pre .blockquote,
    pre .horizontal_rule,
    pre .link {
      color: #ae81ff;
    }
    pre .code {
      color: #a6e22e;
    }
    pre .link_label,
    pre .link_url {
      color: #e6db74;
    }
    pre .link_url {
      font-size: 80%;
    }
    pre .strong,
    pre .strongemphasis {
      font-weight: bold;
    }
    pre .emphasis,
    pre .strongemphasis {
      font-style: italic;
    }
    pre .keyword,
    pre .function,
    pre .change,
    pre .winutils,
    pre .flow,
    pre .lisp .title,
    pre .clojure .built_in,
    pre .nginx .title,
    pre .tex .special {
      color: #F92672;
    }
    pre .corefunction,
    pre .function .keyword,
    pre .class .keyword:first-child {
      color: #66d9ef;
    }
    pre .variable,
    pre .params {
      color: #f8f8f2;
    }
    pre .constant {
      color: #66d9ef;
    }
    pre .class .title {
      color: #f8f8f2;
    }
    pre .title,
    pre .css .class {
      color: #a6e22e;
    }
    pre .class .title:last-child {
      color: #a6e22e;
      font-style: italic;
    }
    pre .attribute,
    pre .symbol,
    pre .symbol .string,
    pre .tag .title,
    pre .value {
      color: #f92672;
    }
    pre .number,
    pre .regexp,
    pre .namespace,
    pre .namespace .keyword,
    pre .alias .keyword,
    pre .literal {
      color: #ae81ff;
    }
    pre .preprocessor {
      color: #f8f8f2;
    }
    pre .alias .keyword:first-child {
      color: #F92672;
    }
    pre .tag .value,
    pre .string,
    pre .css .id,
    pre .subst,
    pre .haskell .type,
    pre .ruby .class .parent,
    pre .built_in,
    pre .sql .aggregate,
    pre .django .template_tag,
    pre .django .variable,
    pre .smalltalk .class,
    pre .django .filter .argument,
    pre .smalltalk .localvars,
    pre .smalltalk .array,
    pre .attr_selector,
    pre .pseudo,
    pre .addition,
    pre .stream,
    pre .envvar,
    pre .apache .tag,
    pre .apache .cbracket,
    pre .tex .command,
    pre .prompt {
      color: #e6db74;
    }
    pre .comment,
    pre .javadoc,
    pre .java .annotation,
    pre .python .decorator,
    pre .template_comment,
    pre .pi,
    pre .doctype,
    pre .deletion,
    pre .shebang,
    pre .apache .sqbracket,
    pre .tex .formula {
      color: #75715e;
    }
    pre .coffeescript .javascript,
    pre .javascript .xml,
    pre .tex .formula {
      opacity: 0.5;
    }
    pre .xml .javascript,
    pre .xml .vbscript,
    pre .xml .css,
    pre .xml .cdata,
    pre .xml .php,
    pre .php .xml {
      opacity: 0.5;
    }

    pre .css .rules,
    pre .css .value,
    pre .css .function {
      color: #f8f8f2;
    }
    pre .css .attribute {
      color: #66d9ef;
    }
    pre .css .tag,
    pre .css .unit,
    pre .css .important {
      color: #f92672;
    }
    pre .hexcolor {
      color: #ae81ff;
    }
```
