### ISSUE TITLE
YAML comments break rendering

### ISSUE THREAD

**Issue by maximal** [highlightjs/highlight.js#2137]
YAML:

```yaml
tag: ЗаказКлиента
type: lead
idTag: outer/inner/ID1C
fields:
  - tag: Номер
    # Тег в XML
    # И поле на стороне Б24
    field: NUMBER
  - tag: Дата
    field: DATE_CREATED
  - tag: Название
    field: NAME
  - tag: Стадия
    field: UF_6666
  - tag: Комментарий
    field: UF_6666
```

Render:

![image](https://user-images.githubusercontent.com/980679/65509177-89581a00-deda-11e9-96a7-dc11293edc0a.png)
