### ISSUE TITLE
Bootstrap 3 conflicts

### ISSUE THREAD

**Issue by mnapoli** [highlightjs/highlight.js#304]
Hi,

Thanks for the project, very cool!

I used it in combination with Bootstrap 3, and had to add the following CSS rules to get it to show correctly:

``` css
pre, code {
    background: #f8f8ff;
    font-family: monospace;
}
```

The background color here is not really important (it's the github theme), the thing is bootstrap applies a background to the `<pre>` and highlight.js to the `<code>`, so we can see a bit of the `<pre>` and its different background color.

I didn't do a pull request because maybe that has already been discussed.
