### ISSUE TITLE
enh(css-like) custom attributes should highlight as `attr`, including the `--`

### ISSUE THREAD

**Issue by thanoskrg** [highlightjs/highlight.js#3237]
Hello and thanks for this amazing library! I am using it for my blog to highlight code snippets, and recently I used CSS highlighting on a code example which included CSS variables.

More specifically I have this case:

```css
/* default context vars */
body {
  --color: black;
  --background-color: lightgrey;
}

/* dark theme context vars */
body.dark {
  --color: lightgrey;
  --background-color: black;
}

/* selector with styles using vars */
main {
  color: var(--color);
  background-color: var(--background-color);
  transition: background-color 0.2s ease-in-out;
}
```

The output looks like this:

![Screenshot 2021-06-11 at 10 05 44 AM](https://user-images.githubusercontent.com/22836902/121645284-b082c080-ca9c-11eb-999a-cb353af58f47.png)

Normally, I would expect that the prefixing `--` of the variables would have been handled as part of the attribute.

I am thinking of forking this repo to introduce a PR addressing this issue. What do you think?
