### ISSUE TITLE
[Request] Auto use dark/light theme depending on prefers-color-scheme

### ISSUE THREAD

**Issue by Deleplace** [highlightjs/highlight.js#3652]
Thank you so much for the awesome library!!!

**Is your request related to a specific problem you're having?**
The custom download contains many light and dark themes, however it doesn't seem to take the CSS media query [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) into account. 

**The solution you'd prefer / feature you'd like to see added...**
In my ideal world, websites would feature both a light theme and a dark theme. The user wouldn't need to explicitly choose in each site, because websites would infer this information from the user preference at the browser level or at the OS level. This is what "prefers-color-scheme" does.

Was this considered for highlight.js? I'd love to see such a nice UX feature.

**Any alternative solutions you considered...**
The CSS media queries don't make it obvious how to fetch an alternative CSS file when "prefers-color-scheme" is "dark". This would save a few kB, but may also incur at least 1 additional round-trip to the server.

However, the CSS of each highlight.js theme is very samll (~1kB) so I'm okay with bundling 1 light theme and 1 dark theme together, and use only 1 of the 2 at any given time.
This is how my build script manually bundles them:
``` 
echo -e "@media (prefers-color-scheme: light) {\n  " > bundle_theme.css
cat css/hljs/default.min.css >> bundle_theme.css
echo -e "\n}\n@media (prefers-color-scheme: dark) {\n  " >> bundle_theme.css
cat css/hljs/dark.min.css >> bundle_theme.css
echo -e "\n}" >> bundle_theme.css
```

**Additional context...**
I recently implemented the dark theme of [Programming-Idioms.org](https://programming-idioms.org/), which required first to move away from the abandoned library [code-prettify](https://github.com/googlearchive/code-prettify).

**Comment by joshgoebel** [comment]
Perhaps relevant?

https://blog.jim-nielsen.com/2019/conditional-syntax-highlighting-in-dark-mode-with-css-imports/

**Comment by joshgoebel** [comment]
Closing as this is more of a website configuration/styling thing than anything we'd add to the library itself.  If someone wanted to contribute a tool to build such themes we'd be happy to link to it... or perhaps turn your build script into a page on the wiki?

**Comment by Tachi107** [comment]
> Closing as this is more of a website configuration/styling thing than anything we'd add to the core library itself.

What about having an `auto.css` style that conditionally includes `default.css` when using a light color scheme and `dark.css` when using a dark one?

**Comment by joshgoebel** [comment]
How? With `@import`?

**Comment by taufik-nurrohman** [comment]
@joshgoebel @Tachi107

~~~ html
<link href="/styles/base16/solarized-dark.css" media="(prefers-color-scheme: dark)" rel="stylesheet">
<link href="/styles/base16/solarized-light.css" media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)" rel="stylesheet">
~~~

**Comment by joshgoebel** [comment]
I think we'll draw a line in the sand and say a first-party theme (for our purposes) is a **singular** set of colors - if a theme has both a light and dark variant - that is two themes, two CSS files, etc.

This is historically how it's been done, and our theme previewer also assumes such.  Changing this would mean:

- We'd need to pair all our existing paired themes (to be consistent).
- We'd have no easy way to pair Base16 schemes.
- We'd need extra work/programming for the theme previewer to be able to show these themes

I'm not seeing the value proposition - and it's also possible someone might want to choose entirely different themes for light and dark mode (rather than a set)... so leaving the power in their hands seems best.

**Comment by Tachi107** [comment]
@joshgoebel thank you very much for your exhaustive reply, I understand your concerns.

As using light and dark theme variants dynamically is extremely easy, I'll just use the solution mentioned above.

**Comment by Deleplace** [comment]
Thanks all for this great discussion. It is indeed not very hard for users to implement the auto-selection themselves, either with conditional include (saving kB) or with a media query inside a custom-made bundled CSS (saving latency).

**Comment by tedspare** [comment]
> ### Option 1
> ```css
> @import url('/styles/base16/solarized-dark.css') screen and (prefers-color-scheme: dark);
> @import url('/styles/base16/solarized-light.css') screen and (prefers-color-scheme: light);
> ```

For anyone returning, this worked for me in a root **styles.css** with Tailwind media-based darkmode:

```css
@import url('highlight.js/styles/github-dark.css') screen and (prefers-color-scheme: dark);
@import url('highlight.js/styles/github.css') screen and (prefers-color-scheme: light);
```

Thanks from the future, @taufik-nurrohman!

**Comment by abwalfdltnha178** [comment]
> @joshgoebel @Tachi107
> 
> ### Option 1
> ```css
> @import url('/styles/base16/solarized-dark.css') screen and (prefers-color-scheme: dark);
> @import url('/styles/base16/solarized-light.css') screen and (prefers-color-scheme: light);
> ```
> 
> ### Option 2
> ```
> <link href="/styles/base16/solarized-dark.css" media="(prefers-color-scheme: dark)" rel="stylesheet">
> <link href="/styles/base16/solarized-light.css" media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)" rel="stylesheet">
> ```

# Hello
What this code in **option 2**?
```txt
(prefers-color-scheme: no-preference) 
```

**Comment by mobeigi** [comment]
I was recently using the technique used by the Highlight.js demo:
https://github.com/highlightjs/highlight.js/blob/main/demo/demo.js

Which involved using JS to enable / disable one of two `<link>` in the head.
This worked but the switch had a bit of flicker or delay to it.

Instead, i've switched to using a single highlightjs CSS file with CSS variables to control it. The result is very fast theme changes.

# Use one `highlightjs.css` file that has been edited to support CSS variables:
```css
/*!
  Theme: MoBeigi.com
  Author: Mo Beigi
  License: See base16-schemes-source
  Maintainer: Mo Beigi
  Version: 2024.10.18

  Based on the Highlight.js Base16 template builder.
  Powered by CSS variables.
  
  https://github.com/highlightjs/base16-highlightjs
*/

pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}

code.hljs {
  padding: 3px 5px;
}

.hljs {
  color: var(--highlightjs-base05);
  background: var(--highlightjs-base00);
}

.hljs::selection,
.hljs ::selection {
  background-color: var(--highlightjs-base02);
  color: var(--highlightjs-base05);
}

/* Comments, Invisibles, Line Highlighting */
.hljs-comment {
  color: var(--highlightjs-base03);
}

/* Tags */
.hljs-tag {
  color: var(--highlightjs-base04);
}

/* Caret, Delimiters, Operators */
.hljs-subst,
.hljs-punctuation,
.hljs-operator {
  color: var(--highlightjs-base05);
}

.hljs-operator {
  opacity: 0.7;
}

/* Variables, XML Tags, Diff Deleted */
.hljs-bullet,
.hljs-variable,
.hljs-template-variable,
.hljs-selector-tag,
.hljs-name,
.hljs-deletion {
  color: var(--highlightjs-base08);
}

/* Integers, Constants, Markup Link Url */
.hljs-symbol,
.hljs-number,
.hljs-link,
.hljs-attr,
.hljs-variable.constant_,
.hljs-literal {
  color: var(--highlightjs-base09);
}

/* Classes, Bold Text */
.hljs-title,
.hljs-class .hljs-title,
.hljs-title.class_ {
  color: var(--highlightjs-base0A);
}

.hljs-strong {
  font-weight: bold;
  color: var(--highlightjs-base0A);
}

/* Strings, Inherited Class */
.hljs-code,
.hljs-addition,
.hljs-title.class_.inherited__,
.hljs-string {
  color: var(--highlightjs-base0B);
}

/* Support, Escape Characters */
.hljs-built_in,
.hljs-doctag,
.hljs-quote,
.hljs-keyword.hljs-atrule,
.hljs-regexp {
  color: var(--highlightjs-base0C);
}

/* Functions, Methods */
.hljs-function .hljs-title,
.hljs-attribute,
.ruby .hljs-property,
.hljs-title.function_,
.hljs-section {
  color: var(--highlightjs-base0D);
}

/* Keywords, Selectors */
.hljs-type,
.hljs-template-tag,
.diff .hljs-meta,
.hljs-keyword {
  color: var(--highlightjs-base0E);
}

.hljs-emphasis {
  color: var(--highlightjs-base0E);
  font-style: italic;
}

/* Deprecated, Embedded Tags */
.hljs-meta,
.hljs-meta .hljs-keyword,
.hljs-meta .hljs-string {
  color: var(--highlightjs-base0F);
}

.hljs-meta .hljs-keyword,
.hljs-meta-keyword {
  font-weight: bold;
}
```

Then elsewhere in your code, set the appropriate styled based on `media screens` or `data-theme` or whatever else you use to control your theme.

```css
  /* Light Theme */
  [data-theme='light'] {
    --highlightjs-base00: #f9f9f9; /* Default Background */
    --highlightjs-base01: #e7eaec; /* Lighter Background */
    --highlightjs-base02: #cceae7; /* Selection Background */
    --highlightjs-base03: #9f9f9f; /* Comments, Invisibles, Line Highlighting */
    --highlightjs-base04: #8796b0; /* Dark Foreground */
    --highlightjs-base05: #404040; /* Default Foreground */
    --highlightjs-base06: #404040; /* Light Foreground */
    --highlightjs-base07: #ffffff; /* Light Background */
    --highlightjs-base08: #ff5370; /* Variables, XML Tags */
    --highlightjs-base09: #f76d47; /* Integers, Constants */
    --highlightjs-base0A: #ff914d; /* Classes, Bold Text */
    --highlightjs-base0B: #91b859; /* Strings, Markup Code */
    --highlightjs-base0C: #39adb5; /* Support, Escape Characters */
    --highlightjs-base0D: #6182b8; /* Functions, Methods */
    --highlightjs-base0E: #7c4dff; /* Keywords, Selectors */
    --highlightjs-base0F: #e53935; /* Deprecated, Embedded Tags */
  }

  /* Dark Theme */
  [data-theme='dark'] {
    --highlightjs-base00: #232323; /* Default Background */
    --highlightjs-base01: #303030; /* Lighter Background */
    --highlightjs-base02: #353535; /* Selection Background */
    --highlightjs-base03: #a9a9a9; /* Comments, Invisibles, Line Highlighting */
    --highlightjs-base04: #b2ccd6; /* Dark Foreground */
    --highlightjs-base05: #e3e3e3; /* Default Foreground */
    --highlightjs-base06: #e3e3e3; /* Light Foreground */
    --highlightjs-base07: #ffffff; /* Light Background */
    --highlightjs-base08: #f07178; /* Variables, XML Tags */
    --highlightjs-base09: #f78c6c; /* Integers, Constants */
    --highlightjs-base0A: #ffcb6b; /* Classes, Bold Text */
    --highlightjs-base0B: #c3e88d; /* Strings, Markup Code */
    --highlightjs-base0C: #89ddff; /* Support, Escape Characters */
    --highlightjs-base0D: #82aaff; /* Functions, Methods */
    --highlightjs-base0E: #c792ea; /* Keywords, Selectors */
    --highlightjs-base0F: #ff5370; /* Deprecated, Embedded Tags */
  }
 ```
