### ISSUE TITLE
(CSS) `unicode-range` keyword not supported

### ISSUE THREAD

**Issue by kshetline** [highlightjs/highlight.js#4253]
**Describe the issue**

CSS `unicode-range` is not recognized, and subsequent range values are badly parsed.

**Which language seems to have the issue?**

CSS

**Are you using `highlight` or `highlightAuto`?**

highlight

**Sample Code to Reproduce**

```css
@font-face {
  font-family: DroidSans;
  src: url(DroidSans.ttf);
  unicode-range: U+000-5FF, U+1e00-1fff, U+2000-2300;
}
```

Gets highlighted this way:

![Image](https://github.com/user-attachments/assets/a6989eaa-8139-473f-bb0f-5575d338b59f)

**Expected behavior**

More like the way GitHub shows the code above.
